### PR TITLE
Enable testing for sph-viz branch

### PR DESCRIPTION
**Pull request by brittonsmith**
This adds installation requirements for the sph-viz branch, including yt-4.0 and cykdtree and checks out the yt-4.0 branch instead of master.

### CODE REVIEW

**Comment by chummels** [comment]
It looks like we might be able to get past the failures we're having if we use this alternate way of installing `cykdtree` as @ngoldbaum did in the travis testing for `yt-4.0`: https://github.com/yt-project/yt/pull/2164/commits/50fafd462e95d9fb0ddd540735d324af0addb22c

**Comment by brittonsmith** [comment]
@chummels, the inclusion of `cykdtree` into yt has fixed the build issue for the tests. There are now a handful of failures. I'm not sure what you want to do about those. Are we just making a new gold sta

**Comment by chummels** [comment]
Yeah, the errors are from yt-4.0 not matching the answer tests from master.  But I thought this PR included new gold standard for the sph-viz branch, which should fix that.  So I'm confused.

**Comment by brittonsmith** [comment]
I cleared the cache. Maybe that was the issue. Let's see.

**Comment by brittonsmith** [comment]
@chummels this appears to be good to go now.

**Comment by chummels** [comment]
Whoa-sweet!

**Pull request merged**
