### PR TITLE
Be more careful about limiting size of line deposition array.

### PR DESCRIPTION
**Pull request by brittonsmith**
This addresses issue #104.

I've added some additional limits on the size of the spectrum deposition array and stopping criteria for widening the array. I've also added a warning when attempting to deposit lines with more than one million bins.

### CODE REVIEW

**Comment by zhafen** [comment]
The test case I used to check Issue #104 passes with this PR. Thanks!

**Comment by maxbeegee** [comment]
Yes, this seems to resolve #104. Can this PR be merged to master?

**Comment by brittonsmith** [comment]
The failing test occurs when comparing extremely high tau values but only has a relative difference of ~1e-11. This is acceptable to me, so I will update the gold standard and merge this.

**Comment by brittonsmith** [comment]
This PR needs to wait until [PR #2399](https://github.com/yt-project/yt/pull/2399) of yt is merged.

**Pull request merged**
