### PR TITLE
Calculating LOS velocity with relative velocities to account for bulk motion

### PR DESCRIPTION
**Pull request by ibutsky**
Hey @brittonsmith! This is a follow up of pull request #82. Like you suggested, light_ray.py now uses relative velocity_x/y/z fields.

### CODE REVIEW

**Comment by brittonsmith** [comment]
@ibutsky, thanks for this! This looks right to me. The test failures are surprising. We'll have to look further into those. I also just realized your PR is to the `sph-viz` branch. The upcoming release will come from the `master` branch (after which time we'll merge `sph-viz` into `master` for the release after this) so I've issued a separate PR porting your changes there. If the tests pass there, then we can just pull this in and come back to this after the release.

**Comment by brittonsmith** [comment]
@ibutsky, one more update. The tests are passing on the version of this PR issued to the master branch, so the failures here are likely something flakey about the `sph-viz` versions of the tests. 

Would you mind adding the `field_parameters` dict to the `make_compound_ray` function and also adding mention of `field_parameters` to the docstrings of `make_simple_ray` and `make_compound_ray`? After that, this is ready to go.

**Comment by ibutsky** [comment]
@brittonsmith I think it's ready to go!

**Comment by brittonsmith** [comment]
@ibutsky, great! As soon as the tests pass on PR #93, I'll merge that and start working on the release. Thanks!

**Comment by brittonsmith** [comment]
@ibutsky, the failing tests are due to a recent change in yt and have nothing to do with this PR. I have an open PR to yt fixing that. When that is merged, PR #95 can be merged and this PR can be merged, too.

**Comment by ibutsky** [comment]
@brittonsmith, sounds great!  Thanks for taking care of the yt-merge!

**Pull request merged**
