### PR TITLE
Adding support for bulk velocity subtraction

### PR DESCRIPTION
**Pull request by ibutsky**
Small change that subtracts out the user-provided bulk velocity of the galaxy/gas before calculating the total line-of-sight velocity.

### CODE REVIEW

**Comment by brittonsmith** [comment]
Hi @ibutsky, thanks for the PR! This is good functionality to have. I'd like to suggest a different implementation, which would be to call `set_field_parameter` on the `sub_ray` object. This would get around issues that might come up if the user specifically queries the `velocity_magnitude` field on the `LightRay` where you might get a collision between setting it manually and querying it on the `sub_ray` object.

**Comment by ibutsky** [comment]
Thanks for the suggestion @brittonsmith! I just pushed an update. Is that along the lines of what you had in mind?

**Comment by brittonsmith** [comment]
@ibutsky, what I was thinking was something like this:
```
if bulk_velocity is not None:
    sub_ray.set_field_parameter('bulk_velocity', bulk_velocity)
```

Alternatively, we could be more flexible and take in a full `field_parameters` dict and do this:
```
if field_parameters is not None:
    for par, val in field_parameters.items():
        sub_ray.set_field_parameter(par, val)
```

Then, you can remove setting the `velocity_magnitude` field manually. As long as you request that field from the `LightRay`, it would be calculated and returned correctly.

**Comment by brittonsmith** [comment]
Hi @ibutsky, I'm going to try to organize a stable trident release sometime next week (hopefully). Would you like to try and get this merged before then? If not, no problem, we can do more releases later.

**Comment by ibutsky** [comment]
Hey @brittonsmith! Sorry for the delay. I've had my hands busy with a new project and a recent move. What time next week were you thinking of releasing the new stable version? I'd like to try to make this work in time for that.

**Comment by brittonsmith** [comment]
@ibutsky, I don't have a hard deadline. The semester gets going the week after next, so I'd like by the end of next week. I'm happy to give you a couple days to get through this and to work with you on it if needs be.

**Comment by ibutsky** [comment]
> @ibutsky, what I was thinking was something like this:
> 
> ```
> if bulk_velocity is not None:
>     sub_ray.set_field_parameter('bulk_velocity', bulk_velocity)
> ```
> 
> Alternatively, we could be more flexible and take in a full `field_parameters` dict and do this:
> 
> ```
> if field_parameters is not None:
>     for par, val in field_parameters.items():
>         sub_ray.set_field_parameter(par, val)
> ```
> 
> Then, you can remove setting the `velocity_magnitude` field manually. As long as you request that field from the `LightRay`, it would be calculated and returned correctly.

Hey @brittonsmith! I looked a bit more into this, and it looks like there's already functionality to set the sub_ray field parameters. However, although the "bulk_velocity" is being set, I don't see that propagating into the calculation of the peculiar velocity (line 605). Am I missing something?

**Comment by brittonsmith** [comment]
@ibutsky, I see what's happening now. The `velocity_x/y/z` fields do not include the bulk velocity subtraction. Instead, we need to modify this code to use the `relative_velocity_x/y/z` fields. I suggest closing this pull request and issuing a new one with just that change. Do you mind doing that?

**Pull request closed without merging**
